#!/bin/bash
prog="teardown"

n_payload_dir=${NEPHO_NephoPayloadDir-"/var/lib/nepho"}
n_log_dir=${NEPHO_NephoLogDir-"/var/log/nepho"}
now="$(date '+%F %T')"

echo "Beginning run at ${now}" >> ${n_log_dir}/${prog}.log

# Pretty print informational and error messages
function message() {
  case $1 in
    fail ) echo -e "\n\033[0m${prog}: \033[1;31m${2}\033[0m" ;;
    info ) echo -e "\n\033[0m${prog}: \033[1;34m${2}\033[0m" ;;
  esac

  echo "${2}" >> ${n_log_dir}/${prog}.log
}

# Make sure we are in the directory of this script
cd $(dirname "${0}")

message fail "No teardown actions"
exit 0
