#!/bin/bash
prog="deploy"

# Make sure we are in the directory of this script
cd $(dirname "${0}")

# Pretty print informational and error messages
function message() {
  case $1 in
    fail ) echo -e "\n\033[0m${prog}: \033[1;31m${2}\033[0m\n" ;;
    info ) echo -e "\n\033[0m${prog}: \033[1;34m${2}\033[0m\n" ;;
  esac
}

message fail "No deployment actions"
exit 0
