ENV.store('VAGRANT_DEFAULT_PROVIDER', '{{ parameters.VagrantBackend|default('virtualbox') }}' )

Vagrant.configure('2') do |config|
  config.vm.box     = '{{ parameters.BoxName }}'
  config.vm.box_url = '{{ parameters.BoxUrl }}'
  config.vm.guest   = '{{ parameters.GuestType|default('linux') }}'.to_sym

  # Forward standard ports
  config.vm.network :forwarded_port, guest: 80,  host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 443, host: 8443, auto_correct: true

  # Mount a shared folder containing the cloudlet's data files
  config.vm.synced_folder 'payload', '{{ parameters.NephoPayloadDir }}'

  # Call Nepho provisioning scripts if they exist and are executable
  ['bootstrap', 'configure', 'deploy'].each do |f|
    path = File.join('{{ parameters.NephoPayloadDir }}', 'hooks', f)
    config.vm.provision :shell, :inline => <<-SCRIPT
      {%- for k, v in env_vars().items() %}
      export NEPHO_{{k}}='{{v}}'
      {%- endfor %}
      [[ -x #{path} ]] && (echo Running #{path}; #{path})
    SCRIPT
  end
end

# vi: set ft=ruby :
